### ISSUE TITLE
Input Time Series Array Fails

### ISSUE THREAD

**Issue by rafaelhubrig** [spmvg/nfoursid#8]
```
#housekeeping
#_________________________________________________________________________

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from nfoursid.kalman import Kalman
from nfoursid.nfoursid import NFourSID
from nfoursid.state_space import StateSpace
import time
import datetime
import math
import scipy as sp
from pandas_datareader import data as pdr
from IPython.display import display, Latex
from statsmodels.graphics.tsaplots import plot_acf
import yfinance as yfin




#this array should be used as input
#_________________________________________________________________________

import yfinance as yfin
yfin.pdr_override()
spy = pdr.get_data_yahoo('AAPL',start='2022-08-23',end='2022-10-24')
spy['Log Return'] = np.log(spy['Adj Close']/spy['Adj Close'].shift(1))
AAPL=pd.DataFrame((spy['Log Return']))




#this is from the documentation and actually works
#_________________________________________________________________________

pd.set_option('display.max_columns', None)

# reproducable results
np.random.seed(0)  

# create a training-set by simulating a state-space model with this many datapoints
NUM_TRAINING_DATAPOINTS = 1000  

# same for the test-set
NUM_TEST_DATAPOINTS = 20  

INPUT_DIM = 3
OUTPUT_DIM = 2

# actual order of the state-space model in the training- and test-set
INTERNAL_STATE_DIM = 4  

NOISE_AMPLITUDE = .1  # add noise to the training- and test-set
FIGSIZE = 8

# define system matrices for the state-space model of the training- 
# and test-set
A = np.array([
    [1,  .01,    0,   0],
    [0,    1,  .01,   0],
    [0,    0,    1, .02],
    [0, -.01,    0,   1],
]) / 1.01
B = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 1, 1],
]
) / 3
C = np.array([
    [1, 0, 1,  1],
    [0, 0, 1, -1],
])
D = np.array([
    [1, 0, 1],
    [0, 1, 0]
]) / 10

state_space = StateSpace(A, B, C, D)
for _ in range(NUM_TRAINING_DATAPOINTS):
    input_state = np.random.standard_normal((INPUT_DIM, 1))
    noise = np.random.standard_normal((OUTPUT_DIM, 1)) * NOISE_AMPLITUDE

    state_space.step(input_state, noise)

nfoursid = NFourSID(
    
    # the state-space model can summarize inputs and outputs as a dataframe
    state_space.to_dataframe(),
    
    output_columns=state_space.y_column_names,
    input_columns=state_space.u_column_names,
    num_block_rows=10
)
nfoursid.subspace_identification()




#further methods
#_________________________________________________________________________

fig, ax = plt.subplots(figsize=figsize)
nfoursid.plot_eigenvalues(ax)
fig.tight_layout()

#interpret order from plot (sprungstelle), still run order->inf
ORDER_OF_MODEL_TO_FIT = 4
state_space_identified, covariance_matrix = nfoursid.system_identification(
    rank=ORDER_OF_MODEL_TO_FIT
)

#Ausgabe der Modellvorhersagen
nfoursid.to_dataframe()

#Vorhersage gegen Beobachtung
figsize = (1.3 * FIGSIZE, FIGSIZE)
fig = plt.figure(figsize=figsize)

# the state-space model can plot its inputs and outputs
state_space.plot_input_output(fig)  

fig.tight_layout()
```

**Comment by spmvg** [comment]
Hi @rafaelhubrig, thanks for the message! Could you please provide a stacktrace of the failure and the input dataset in for example CSV format?

**Comment by rafaelhubrig** [comment]
Simply setting the AAPL DataFrame as in input in the nfoursid method leads to the following stacktrace:
`nfoursid = NFourSID(
    
    # the state-space model can summarize inputs and outputs as a dataframe
    state_space.to_dataframe(),
    
    output_columns=state_space.y_column_names,
    input_columns=AAPL,
    num_block_rows=10
)
Traceback (most recent call last):

  File "C:\Users\rhubr\AppData\Local\Temp\ipykernel_13700\1148063354.py", line 1, in <cell line: 1>
    nfoursid = NFourSID(

  File "C:\Users\rhubr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nfoursid\nfoursid.py", line 42, in __init__
    self.u_columns = input_columns or []

  File "C:\Users\rhubr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\generic.py", line 1527, in __nonzero__
    raise ValueError(

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

`

This is the CSV of the Pandas DataFrame AAPL:
`'Date,Log Return\r\n2022-08-23 00:00:00-04:00,\r\n2022-08-24 00:00:00-04:00,0.0017923074577483272\r\n2022-08-25 00:00:00-04:00,0.014812482985677418\r\n2022-08-26 00:00:00-04:00,-0.03842831422080679\r\n2022-08-29 00:00:00-04:00,-0.013784690623807348\r\n2022-08-30 00:00:00-04:00,-0.015423842696251215\r\n2022-08-31 00:00:00-04:00,-0.01069196209188781\r\n2022-09-01 00:00:00-04:00,0.004695803473998353\r\n2022-09-02 00:00:00-04:00,-0.01370461256417906\r\n2022-09-06 00:00:00-04:00,-0.00824904889464204\r\n2022-09-07 00:00:00-04:00,0.009211383074740714\r\n2022-09-08 00:00:00-04:00,-0.009664380898669743\r\n2022-09-09 00:00:00-04:00,0.01866446642992849\r\n2022-09-12 00:00:00-04:00,0.03778500314103842\r\n2022-09-13 00:00:00-04:00,-0.06047162766904066\r\n2022-09-14 00:00:00-04:00,0.00950998174297125\r\n2022-09-15 00:00:00-04:00,-0.019111372587537288\r\n2022-09-16 00:00:00-04:00,-0.011020580898704562\r\n2022-09-19 00:00:00-04:00,0.024773451524560654\r\n2022-09-20 00:00:00-04:00,0.015544074915905787\r\n2022-09-21 00:00:00-04:00,-0.02047586088693964\r\n2022-09-22 00:00:00-04:00,-0.0063956446208170295\r\n2022-09-23 00:00:00-04:00,-0.015239326232694429\r\n2022-09-26 00:00:00-04:00,0.0022577043085954714\r\n2022-09-27 00:00:00-04:00,0.00654480959792178\r\n2022-09-28 00:00:00-04:00,-0.012732294860157173\r\n2022-09-29 00:00:00-04:00,-0.05036640575259723\r\n2022-09-30 00:00:00-04:00,-0.030499778101340816\r\n2022-10-03 00:00:00-04:00,0.030289181169838288\r\n2022-10-04 00:00:00-04:00,0.02530033760429883\r\n2022-10-05 00:00:00-04:00,0.002051153289326668\r\n2022-10-06 00:00:00-04:00,-0.006647663575828979\r\n2022-10-07 00:00:00-04:00,-0.03740983567929609\r\n2022-10-10 00:00:00-04:00,0.0023528516214478498\r\n2022-10-11 00:00:00-04:00,-0.010307833978019161\r\n2022-10-12 00:00:00-04:00,-0.0046156614250076975\r\n2022-10-13 00:00:00-04:00,0.03306041404454222\r\n2022-10-14 00:00:00-04:00,-0.0327712135702614\r\n2022-10-17 00:00:00-04:00,0.02870672985132822\r\n2022-10-18 00:00:00-04:00,0.009365372347504503\r\n2022-10-19 00:00:00-04:00,0.0007649225223349846\r\n2022-10-20 00:00:00-04:00,-0.003272423500033539\r\n2022-10-21 00:00:00-04:00,0.0266994918191778\r\n'`

**Comment by spmvg** [comment]
Hi @rafaelhubrig! It looks like a dataframe was passed to an argument that expects a list-of-strings `input_columns=AAPL,`. The `input_columns` parameter is used to indicate the input column(s) of the state-space model. See also this documentation: https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html

If I adjust the code slightly, there is no error:
```
from io import StringIO

import pandas as pd
from nfoursid.nfoursid import NFourSID

aapl_csv = """
Date,Log Return
2022-08-23 00:00:00-04:00,
2022-08-24 00:00:00-04:00,0.0017923074577483272
2022-08-25 00:00:00-04:00,0.014812482985677418
2022-08-26 00:00:00-04:00,-0.03842831422080679
2022-08-29 00:00:00-04:00,-0.013784690623807348
2022-08-30 00:00:00-04:00,-0.015423842696251215
2022-08-31 00:00:00-04:00,-0.01069196209188781
2022-09-01 00:00:00-04:00,0.004695803473998353
2022-09-02 00:00:00-04:00,-0.01370461256417906
2022-09-06 00:00:00-04:00,-0.00824904889464204
2022-09-07 00:00:00-04:00,0.009211383074740714
2022-09-08 00:00:00-04:00,-0.009664380898669743
2022-09-09 00:00:00-04:00,0.01866446642992849
2022-09-12 00:00:00-04:00,0.03778500314103842
2022-09-13 00:00:00-04:00,-0.06047162766904066
2022-09-14 00:00:00-04:00,0.00950998174297125
2022-09-15 00:00:00-04:00,-0.019111372587537288
2022-09-16 00:00:00-04:00,-0.011020580898704562
2022-09-19 00:00:00-04:00,0.024773451524560654
2022-09-20 00:00:00-04:00,0.015544074915905787
2022-09-21 00:00:00-04:00,-0.02047586088693964
2022-09-22 00:00:00-04:00,-0.0063956446208170295
2022-09-23 00:00:00-04:00,-0.015239326232694429
2022-09-26 00:00:00-04:00,0.0022577043085954714
2022-09-27 00:00:00-04:00,0.00654480959792178
2022-09-28 00:00:00-04:00,-0.012732294860157173
2022-09-29 00:00:00-04:00,-0.05036640575259723
2022-09-30 00:00:00-04:00,-0.030499778101340816
2022-10-03 00:00:00-04:00,0.030289181169838288
2022-10-04 00:00:00-04:00,0.02530033760429883
2022-10-05 00:00:00-04:00,0.002051153289326668
2022-10-06 00:00:00-04:00,-0.006647663575828979
2022-10-07 00:00:00-04:00,-0.03740983567929609
2022-10-10 00:00:00-04:00,0.0023528516214478498
2022-10-11 00:00:00-04:00,-0.010307833978019161
2022-10-12 00:00:00-04:00,-0.0046156614250076975
2022-10-13 00:00:00-04:00,0.03306041404454222
2022-10-14 00:00:00-04:00,-0.0327712135702614
2022-10-17 00:00:00-04:00,0.02870672985132822
2022-10-18 00:00:00-04:00,0.009365372347504503
2022-10-19 00:00:00-04:00,0.0007649225223349846
2022-10-20 00:00:00-04:00,-0.003272423500033539
2022-10-21 00:00:00-04:00,0.0266994918191778
"""

aapl_df = pd.read_csv(StringIO(aapl_csv))

nfoursid = NFourSID(
    aapl_df.dropna(),  # training data cannot contain nulls. Depending on your use-case, better cleaning might be needed
    output_columns=['Log Return'],
    num_block_rows=10
)
```

Let me know what you think! I'll close this issue since I think the underlying issue is addressed, but feel free to comment still.
